### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by jonas-jonas** [stuartlangridge/ColourPicker#64]
Is there a way to trigger just the selection tool (not the overview window) with a keyboard shortcut (or from the commandline `$ pick --selection` or something along that)?

**Comment by stuartlangridge** [comment]
You should be able to pass `--pick` to do that, I think.

**Comment by jonas-jonas** [comment]
Ah, thanks that works. That doesn't seem to be documented though? 

Another thing, would it be possible to add a setting to automatically copy the selected color to the clipboard?

**Comment by stuartlangridge** [comment]
It isn't documented because I'm not sure I think it's a good use case, and I haven't tested it in all situations.

I don't think I really want a setting to automatically overwrite the clipboard with a picked colour; Pick's real reason for existence is switching colour formats and seeing a history of colours, so the overview window is important, and copying a colour in your current format is one click away.

It sounds like what you might want is "start up a colour picker, pick a colour, and then immediately exit, putting that colour on the clipboard, and never show the overview window at all"? If it is, then `gpick --single` does precisely absolutely that, and does it well; you may find that useful alongside or as an alternative to `pick`?

**Comment by jonas-jonas** [comment]
Thanks for the fast answers. `gpick --single` is precisely what I want. I was using deepin-picker before but it doesn't work anymore, so I was looking for an alternative.

Thanks for the heads up, will be using that. Closing~
